SELECT REG_ANS, SUM(
        VL_SALDO_FINAL - VL_SALDO_INICIAL
    ) AS DESPESAS_ULTIMO_ANO
FROM (
        SELECT
            REG_ANS, VL_SALDO_FINAL, VL_SALDO_INICIAL, DESCRICAO, data
        FROM `1t2022`
        UNION ALL
        SELECT
            REG_ANS, VL_SALDO_FINAL, VL_SALDO_INICIAL, DESCRICAO, data
        FROM `2t2022`
        UNION ALL
        SELECT
            REG_ANS, VL_SALDO_FINAL, VL_SALDO_INICIAL, DESCRICAO, data
        FROM `3t2022`
        UNION ALL
        SELECT
            REG_ANS, VL_SALDO_FINAL, VL_SALDO_INICIAL, DESCRICAO, data
        FROM `4t2022`
        UNION ALL
        SELECT
            REG_ANS, VL_SALDO_FINAL, VL_SALDO_INICIAL, DESCRICAO, data
        FROM `1t2023`
        UNION ALL
        SELECT
            REG_ANS, VL_SALDO_FINAL, VL_SALDO_INICIAL, DESCRICAO, data
        FROM `2t2023`
        UNION ALL
        SELECT
            REG_ANS, VL_SALDO_FINAL, VL_SALDO_INICIAL, DESCRICAO, data
        FROM `3t2023`
    ) AS t
WHERE (
        DESCRICAO LIKE '%EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR%'
        OR DESCRICAO LIKE '%EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÃŠNCIA A SAÃšDE MEDICO HOSPITALAR%'
    )
    AND data BETWEEN DATE_SUB(NOW(), INTERVAL 1 YEAR) AND NOW()
GROUP BY
    REG_ANS
ORDER BY DESPESAS_ULTIMO_ANO DESC
LIMIT 10;